"""Append the Notion "Column, Op-ed, and Essay" items that are NOT already
covered by the migrated Naver blog archive (app/data/naver-archive.json),
and rename the merged result to app/data/writing-archive.json.

Unlike the Naver import, these items only have a title/outlet/link/short
excerpt (no scraped full body or thumbnail) - see conversation for why:
mirroring 40+ external articles' full text wasn't worth the added scope.
Detail pages fall back to the excerpt + an outbound link when body is empty.

kind: "post" for the person's own writing, "press" for third-party coverage
about him (interviews/news reports) - the site renders a [보도] ribbon on
"press" rows so readers don't mistake them for his own writing.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "app" / "data" / "naver-archive.json"
DST = ROOT / "app" / "data" / "writing-archive.json"

NEW_ENTRIES = [
    # -- own writing: full text supplied directly (원 웹진이 없어져 원문
    # 링크가 없음 - 본인이 제공한 원고 전문을 그대로 싱글 페이지로 게시) --
    dict(slug="col-webzinex-2023-chatgpt", title="ChatGPT를 활용한 대학 수업",
         publication="웹진X", year="2023", month="4", day="15", section="칼럼", kind="post",
         sourceUrl=None, excerpt=None,
         body=[
             "1. 지금 여기에 있는 미래",
             "최근 들어 디지털 대전환의 시기에 살고 있음을 체감하고 있다. 계속해서 새로운 생성형 인공지능 서비스가 등장하고 나날이 업데이트되고 있기 때문이다. 레이 커즈와일(Raymond \"Ray\" Kurzweil)이 말한 '특이점(singularity)'이 정말 멀지않은 것만 같다. 그럼에도 ChatGPT를 비롯한 생성형 인공지능 서비스를 둘러싼 작금의 열풍은 다소 야단스럽다. 아마도 지금 우리가 목도하고 있는 변화가 가속화될 때 벌어질 수 있는 일에 대한 (예비적) 기대와 우려가 투영되어 있기 때문일 것이다.",
             "앞으로 어떤 일이 벌어질지 예상하는 것은 물론 흥미롭고 중요한 일이다. 대학 구성원들 역시 이 문제에 주목해 왔다. 일례로 내가 소속된 연세대학교 정치외교학과 BK21 교육연구단 역시 '혁신 과학기술 시대의 정치적 문제'를 식별하고 이를 해결하기 위한 방안을 모색하는 것을 핵심 과제로 설정하고 있다.",
             "디지털 대전환을 중심으로 하는 혁신 과학기술의 발전이 미래의 대학 교육에 근본적인 변화를 가져올 것이라는 점 역시 분명해 보인다. 이러한 변화를 예상하고 이에 대한 대응 방안을 모색하는 것은 매우 중요한 문제다. 그러나 ChatGPT가 가져온 현재적 충격의 핵심은 우리가 미래라고 생각했던 것이 '이미 지금 여기에 와 있다'는 느낌을 준다는데 있다. '미래에 기술이 발전한다면...'이라고 가정했던 것들이 (충분히 만족스러운 수준은 아니지만) 우리 눈앞에 지금 존재하고 있다고 인식하게 된 것이다.",
             "이에 따라 '미래의 대학 교육' 역시 이제 상상이 아니라 구현의 대상이 됐다. 교수와 학생을 비롯한 대학 구성원들은 '아이언맨의 자비스'까지는 아니더라도 그 '가능태'로 간주되는 것들을 이미 활용하고 있다. 미래에 대응하기 위해 준비해야 하는 것이 아니라, 이미 도래한 미래와 함께 지금 여기서 새로운 대학 교육이 이루어지고 있는 것이다. 이 글에서는 지금 여기에 도래한 변화에 주목하고자 하면서, 새롭게 등장한 생성형 인공지능 서비스를 대학 수업에서 내가 어떻게 활용하고 있는지 이야기하고자 한다.",
             "대단히 특별한 이야기는 아니다. 나보다 더 먼저, 적극적으로 대학 수업에서 ChatGPT 같은 새로운 서비스를 활용한 사례도 물론 있다. 다만, 최근의 변화와 가장 거리가 먼 것처럼 보이는 학문분과의 수업에서 현재 벌어지고 있는 하나의 사례 정도로 이해될 수는 있을 것이다. 지금 이 순간 우리의 '삶이라는 용광로'에 생성형 인공지능이 더해지면서 발생한 화학반응에 대한 소소한 기록인 셈이다.",
             "2. 현대정치사상 수업의 목적",
             "이번학기 나는 연세대학교 정치외교학과에서 학부생을 대상으로 개설한 <현대정치사상(Contemporary Political Thought)> 수업을 담당하고 있다. 외국인 유학생과 교환학생이 다수 포함된 영어수업이다. 이 수업명은 현대정치사상에 대한 개괄적 지식을 전달할 것을 요구한다. 이에 따라 이 수업의 일차적 목적은 자연스럽게 보수주의, 공화주의, 자유주의, 사회주의, 공산주의 등 다양한 이념에 관한 지식을 전달하는 것, 그리고 그 과정에서 학생들이 중요한 1차 문헌들의 내용을 이해하도록 돕는 것 정도가 될 것이다.",
             "그러나 대학 수업으로서 <현대정치철학>에서 지식 전달 그 자체가 궁극적 목적이 될 수는 없다. ChatGPT까지 갈 것도 없이, 이와 관련된 지식 전달을 목적으로 하는 수많은 대안들이 대학 바깥에 이미 넘쳐난다. 이런 상황에서 이 과목이 대학 교육의 일환으로 존재해야하는 또 다른 이유가 있어야 하는데, 이것이 곧 시대적 변화에 발맞춰 새로운 목표를 설정해야 한다는 것을 의미하지는 않는다.",
             "애초에 <현대정치철학>이라는 제목의 대학 수업의 궁극적 목표는 학생들이 이를 공부함으로써 주요한 정치개념, 정치사상, 정치현실, 그리고 정치 그 자체에 대해 더 깊이 생각할 수 있는 '지적 근육'을 키우는 것이다. 근육을 키우기 위해 반복적 중량운동이 필요한 것과 마찬가지로, 이러한 종류의 지적 능력을 함양하기 위해서는 읽고 쓰고 말하는 과정이 필수적이다. 그리고 이 과정에서 굳이 우리가 지금 여기에 모여서 같은 내용을 공부한다는 의미를 최대화하기 위해, 나와 학생들 사이의 소통뿐만 아니라 학생들 간의 소통 역시 극대화할 필요도 있다.",
             "익히 알다시피, 읽고 쓰고 말하면서 스스로 생각하는 능력을 배양하는 교육은 과거는 물론이고 '좋은 질문'의 중요성이 더욱 강조되고 있는 현재, 그리고 미래에도 반드시 요구되는 것이다. 이것이 수업 목적의 전면적 수정이 아니라, 학생들에게 현대정치철학을 공부한다는 것의 이러한 현재적 의미를 상기시켜주는 것만으로 충분한 이유다.",
             "3. 블렌딩 수업의 경험",
             "이처럼 수업의 궁극적 목적은 바뀌지 않았지만, 이런 목적을 달성하기 위한 방법은 변했다. 우선, 이 수업은 1시간의 온라인 녹화 수업과 2시간의 오프라인 수업을 혼합한 '블렌딩 방식'을 채택하고 있다. 수업 목적 중 지식 전달 부분은 반복학습이 보다 중요하기 때문에 강의 중심의 온라인 녹화 수업으로 구성하는 한편, 오프라인 수업은 수업 구성원 간의 쌍방향 소통에 초점을 맞춰 질의응답, 전체토론, 그룹활동을 중심으로 구성한 것이다.",
             "개인적 경험에 비춰보면, 블렌딩 수업에 대한 학생들의 선호도가 상당히 높게 확인된다. 코로나19가 야기한 특수한 교육 환경과 이를 가능하게 한 디지털 기술이 결합되면서 새로운 수업 방식이 제도적으로 정착된 사례, 즉 '뜻하지 않게 지금 구현된 미래'로 볼 수 있다. 시간과 장소의 제약으로부터 비교적 자유롭다는 점은 수업 구성원 모두에게 장점이 된다. 또한 앞서 언급한 것처럼 강의 내용을 언제든 복기할 수 있다는 점은 오프라인 수업이 제공해주기 어려운 장점이자, 디지털 기술이 결합된 여러 대안적 교육방식들이 공통되게 목표로 하는 바이기도 하다.",
             "그러나 지난 몇 년간 비대면 수업을 경험한 결과, 여러 장점에도 불구하고 뚜렷한 한계 역시 확인할 수 있었다. 일반적으로는 비대면 수업의 경우 학생들의 수업 집중도를 확인할 수 없다는 점이 주로 지적되었다. 그러나 보다 근본적인 문제는 비대면 수업이 정보전달에 집중하는 일방적 강의가 될 가능성이 높고, 수업 구성원 간의 소통에 한계가 존재한다는 점이다. 특히 후자의 문제에 대응하기 위해 비대면 상황에서도 상호작용을 최대화하기 위해 연세대학교의 온라인 교육 플랫폼인 런어스뿐만 아니라, 클라썸, 카카오 오픈챗 등 다양한 서비스를 활용했다. 이러한 경험은 새롭게 등장한 생성형 인공지능 서비스를 수업에 활용하는 밑거름이 됐다. 자각하지 못하는 사이에 수업 구성원들이 대학 강의실 바깥에서 상호 소통하고 학습하는 경험이 자연스럽게 축적되어 온 것이다.",
             "4. 온라인 강의노트",
             "이 수업의 첫 번째 특징은 강의시간에 활용할 파워포인트 자료를 만드는 대신, 공식적인 수업 시간 전에 이번 주에 배우게 될 내용을 정리한 강의노트를 노션(Notion.so)을 통해 제공한다는 점이다. 여기에는 수업의 전체적 흐름에 따라 핵심적인 내용이 모두 포함되어 있는데, 예컨대 1960년대의 대표적인 1차 자료들을 읽은 가장 최근의 7주차 수업의 경우에 온라인 강의노트에 (1) 1960년대의 시대적 배경, (2) 저자에 대한 간략한 소개, (3) 읽기 자료의 챕터별 주요 내용, (4) 생각해볼 거리(함의) 등이 포함되어 있다.",
             "강의노트를 온라인으로 공유하는 것은 매우 도전적인 과제이며, 많은 시간과 노력이 요구된다. 그럼에도 불구하고 워드 파일로 강의노트를 만들고 이를 다시 요약해서 파워포인트로 만드는 과거의 방식에 비해 간편한 부분도 있다. 주요 내용과 이미지를 압축적으로 제시할 수밖에 없는 파워포인트에 비해, 훨씬 많은 정보를 구체적으로 제공할 수 있을 뿐만 아니라 파워포인트에 비해 페이지구성이나 디자인에 시간을 쓸 필요가 없다는 장점을 가지기 때문이다. 다양한 멀티미디어 자료와 외부링크를 쉽게 임베드할 수 있다는 점 역시 큰 강점이다.",
             "학생들은 이 온라인 강의노트의 특정한 부분을 선택해 이와 관련된 질문이나 지식을 댓글 형태로 공유할 수 있는데, 이는 강의실 바깥에서의 소통을 촉진하기 위한 첫 번째 수단으로 활용되고 있다. 강의실 밖 소통을 위한 다른 수단으로 비대면 수업 당시 활용했던 카카오 오픈 채팅방 역시 운영하고 있다. 전자는 수업 내용에 대한 토론 창구로서, 후자는 수업과 관련된 일상적 질의응답 창구로서의 성격이 강하다. 한편, 이 수업이 영어로 진행된다는 점 역시 강의노트를 제공하게 된 계기 중 하나인데, 학생들에게 문자화된 정보를 제공함으로써 DeepL과 같은 인공지능 번역 서비스를 보다 편리하게 활용할 수 있도록 한 것이다. 강의노트는 줌이나 클로바에서 획득할 수 있는 자동녹취 스크립트보다 정제된 텍스트라는 점에서 번역 기능을 활용하기에 더 용이한 측면이 있다.",
             "5. 인공지능 조교의 활용",
             "강의노트 작성에서 가장 도움이 되는 것은 ChatGPT를 활용한 브레인스토밍과 노션의 유료 인공지능 서비스를 이용한 요약 및 정리다. ChatGPT는 주로 위 강의노트 구성요소 중 (1)과 (2)를 위해 활용하고 있는데, 뚜렷한 한계도 있다. 기본적인 정보를 제외하면 할루시네이션의 가능성이 높기 때문에 교차검증이 필수적이기 때문이다. 오히려 할루시네이션이 예상치 못한 생각의 가능성을 열어준다는 점에 주목하며 활용하는 편이다. 최신정보나 확실한 출처가 필요한 경우에는 Bing A.I. 역시 사용하고 있지만, 아직까지는 새로운 검색방식에 가까울 뿐 '생성'이라는 측면에서는 큰 효용을 느끼지는 못하고 있다.",
             "강의노트 작성 시에는 ChatGPT 보다는 매개변수(parameter)를 의도적으로 제한할 수 있는 생성형 인공지능을 더 유용하게 활용되고 있다. 특히 (3)과 관련해서 ChatGPT를 활용한 ChatPDF 서비스가 매우 유용한데, ChatGPT와 달리 업로드한 PDF 파일에 대해서만 대화할 수 있다는 점이 특장점이다. 한편, 노션 인공지능은 강의노트의 전체적 내용을 다듬는데 활용하고 있다. ChatPDF의 사례와 마찬가지로, 내가 현재 노션 페이지에 작성한 내용에 한정해 대화할 수 있다는 점이 특장점이기 때문이다.",
             "전체적인 강의 방향과 내용을 브레인스토밍하고, 이와 관련해 메모했던 것을 문장으로 바꿔주고, 읽기 자료에 대한 설명과 해석을 요약하거나 다듬는데 큰 도움을 준다는 점에서 생성형 인공지능은 조교로서의 역할을 톡톡히 하고 있다. 추후 내가 작성한 강의노트에 대해 제한된 생성형 인공지능 채팅 기능을 적용할 수 있게 된다면, 읽기 자료나 수업 내용에 대해 학생들이 질문할 경우에도 인공지능 조교가 대신 대답해주는 것 역시 가능해질 것으로 기대하고 있다.",
             "6. 온라인 매거진",
             "이러한 경험에 기초해 학생들에게도 생성형 인공지능 서비스를 적극적으로 활용하도록 권장하고 있다. 이번 수업에서는 시험 대신 현대정치철학을 주제로 한 온라인 잡지를 만드는 것을 공통과제로 설정했다. 지금까지 대학 수업에서 학생들이 과제로 작성한 에세이는 문서 파일의 형태로 개인 폴더에 저장되어 사장되거나, 기껏해야 족보 혹은 표절 검사를 위한 소스로 활용될 뿐이었다. 이 에세이를 모아서 온라인 잡지 형식으로 발간하는 것은 학생들의 글을 널리 공유하고자 하는 목적도 있지만, 대부분의 생성형 인공지능 서비스가 온라인에 존재하는 데이터를 스크래핑해서 활용하고 있다는 점에서 착안한 것이기도 하다. 요컨대 학생들이 지식 데이터의 수요자일뿐만 아니라 공급자라는 점을 자각하게 하는 하나의 방법이 될 수 있는 것이다.",
             "또한 온라인 잡지의 형식을 갖추기 위해 학생들이 주제에 따라 자발적으로 팀을 형성하고, 팀 리더들이 편집위원회를 구성하도록 했다. 각각의 팀은 자신들이 설정한 주제에 따라 온라인 잡지의 한 섹션을 만들게 되는데, 이 과정에서 ChatGPT, DeepL뿐만 아니라 Midjourney 같은 인공지능 이미지 생성 서비스 역시 적극적으로 활용하도록 권장하고 있다. 일례로 애니메이션과 현대정치철학을 주제로 설정한 팀에서는 특정 애니메이션에 대한 자신의 해석을 팀원뿐만 아니라 ChatGPT와 함께 논의하는 형식으로 발전시키고 있다. 그 첫 번째 결과물을 중간고사 기간 이후 온라인 잡지의 제1호로 게시될 것이다.",
             "최근 여러 대학에서 발표한 ChatGPT 활용 지침은 마치 자신의 생각과 ChatGPT의 생각을 명확하게 구분할 수 있을 것이라고 믿고 있는 듯하지만, 개인적으로 이는 불가능하다고 생각한다. 따라서 생성형 인공지능 서비스를 활용해 에세이라는 결과물을 도출해 나가는 과정에서 내가 학생들에게 요구한 것은 (무엇이 자기 생각인지, 무엇이 ChatGPT의 생각인지를 구분하고 명시하는 것이 아니라) 일련의 상호작용 과정 자체를 기록하는 것이다. 지금에야 프롬프트 엔지니어(Prompt Engineer)가 유망직종으로 간주되지만, 이것이 결국에는 초거대 인공지능과의 소통하는 능력 내지는 역량을 의미한다는 점을 상기하면, 학생들이 본인의 '지적 근육'을 성장시켜나가는 과정에서 인공지능을 적극적으로 활용함으로써 이러한 역량을 함양할 수 있도록 교육하는 것이 더 중요하다고 생각하기 때문이다.",
         ]),
    # -- own writing: issue briefs / policy pieces --
    dict(slug="col-aibasicact-2026-01", title="Korea's AI Law Has an Official English Name. Almost No One Uses It.",
         publication="AI Basic Act (aibasicact.kr)", year="2026", month="8", section="이슈브리프", kind="post",
         sourceUrl="https://lnkd.in/genWCMjt",
         excerpt="Kyungho Song & Bongkyung Cho. 「Framework Act on the Development of Artificial Intelligence and the Creation of a Foundation for Trust」라는 공식 영문 명칭과 통용되는 약칭 'AI Basic Act' 사이의 간극을 다룬 aibasicact.kr의 첫 블로그 글."),
    dict(slug="col-undp-2025", title="Building Safer AI for All Languages: A Collective Pathway to Inclusive Human Development",
         publication="UNDP Digital, AI and Innovation Hub", year="2025", section="칼럼", kind="post",
         sourceUrl="https://www.undp.org/digital/blog/building-safer-ai-all-languages-collective-pathway-inclusive-human-development",
         excerpt="Dr. Kyungho Song & Dr. Jiyeon Cho (Korea AI Safety Institute)와 UNDP Digital, AI and Innovation Hub의 공동 기고.",
         note={
             "text": "국문 번역",
             "url": "https://www.aisi.re.kr/kor/article/ATCL75b4fb0a5/95?ptSignature=myq8exWppBvlsub5Sr8a78bbxNkUKo%2FOOa%2BANLitP%2BRowKOb42MhFxHrU0ICe2q3LdIPbqDkrRvJdrTsOsGp9dnU11bqw0oMz45R%2FI9IYLDzXT6qglQn6l1onjnE29oiEv8nRNgTLWhnXaSC9Es%2FmmMJGpdzRzCBZOlC0j%2BazP4dITmIZzhvti5pxvJNK0MtAU2DH7rZuWZAq7ixMWupri8LXwk6UA%2Bi%2Bk0vO39Dc9CE3TpQgizHo6bogvNJseNkQ0MhgRjeEvYesH0QCgy2IwY0AC%2FL5%2Fbu%2B4Wc9bkI4aLECV7CTFUKKerHXWy%2FDminxGowg4JOTGGaG60D3IAWVqHkTOhk%2FhWX54x3e7xI1G7qcE8LIEOacSfqILj0gi0AcNczEDeoQl%2BjvStpZj5Qog%3D%3D&csSignature=otfgVv%2FgBQVw2Shwj0QlXA%3D%3D&mno=&pageIndex=3&searchCondition=&searchKeyword=",
         }),
    dict(slug="col-korea-univ-2026", title="[Issues & Insights 33호] 미토스 충격과 한국의 사이버 보안 전략",
         publication="고려대학교 경제기술안보연구원", year="2026", section="이슈브리프", kind="post",
         sourceUrl="https://iets.korea.ac.kr/iets/books/publication.do?mode=view&articleNo=808225",
         excerpt=None),
    dict(slug="col-koreaonpoint-2025", title="The Political Philosophy of REAIM: Rethinking Autonomous Weapon Systems in A Just War Theory Perspective",
         publication="한국국제정치학회 Korea on Point", year="2025", section="이슈브리프", kind="post",
         sourceUrl="https://koreaonpoint.org/view.php?idx=390",
         excerpt="As autonomous weapon systems (AWS) based on AI are increasingly integrated into military operations worldwide, international cooperation needs to establish ethical norms, and the legal framework..."),
    dict(slug="col-cdss-56", title="디지털사회 제56호: 게이머의 정치적 주체화와 디지털 공론장의 가능성",
         publication="연세대학교 디지털사회과학센터 [디지털사회]", year="2025", section="이슈브리프", kind="post",
         sourceUrl="http://cdss.yonsei.ac.kr/index.php/issue-brief/?uid=205&mod=document&pageid=1",
         excerpt="게이머들이 단순히 게임을 통해 여가를 즐기는 집단을 넘어 중요한 사회적, 정치적 행위자로 부상하고 있다."),
    # -- 프레시안 특집 --
    dict(slug="col-pressian-vote-2024", title="'한국인도 미국 대선 투표권을 허하라'가 헛소리라고요?",
         publication="프레시안 특집", year="2024", month="9", day="12", section="칼럼", kind="post",
         sourceUrl="https://www.pressian.com/pages/articles/2024091218534053511",
         excerpt="2024년 11월 5일, 60번째 미국 대통령 선거가 치러진다. 한국의 언론 보도나 기사 댓글, 인터넷 커뮤니티 게시물을 살펴보면, 우리 대선 못지 않게 미국 대선에 대한 관심이 뜨겁다."),
    # -- 프레시안 특집 [이세계 민주주의 교실] (series, 2024.02.08) --
    dict(slug="col-pressian-isekai-1", title="트럭에 치여 '이세계'에서 눈뜬 당신의 '정치적 선택'은?",
         publication="프레시안 특집 [이세계 민주주의 교실]", year="2024", month="2", day="8", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024020810512758680",
         excerpt="당신은 트럭에 치여 이세계(異世界)에서 눈을 떴다. 주위를 둘러보니 혼자는 아니다. 수십 명의 지구인과 함께 있다."),
    dict(slug="col-pressian-isekai-2", title="미국이나 한국이나…이재명과 매카시, 문제는 포퓰리즘?",
         publication="프레시안 특집 [이세계 민주주의 교실]", year="2024", month="2", day="8", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024020814370080497",
         excerpt="지구가 아닌 이세계에서 눈을 뜬 당신 앞에 주어진 과제는 '마법으로 드래곤 사냥하기'가 아닌, 평범한 사람들이 모여 공동의 문제를 해결할 '도구'로서의 정치체제를 만드는 것이었다."),
    dict(slug="col-pressian-isekai-3", title="'정체성 정치'의 역습…극우 이민혐오가 백인의 '정체성'?",
         publication="프레시안 특집 [이세계 민주주의 교실]", year="2024", month="2", day="8", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024020814440909082",
         excerpt="지구가 아닌 이세계에서 눈을 뜬 당신 앞에 주어진 과제는 '마법으로 드래곤 사냥하기'가 아닌, 평범한 사람들이 모여 공동의 문제를 해결할 '도구'로서의 정치체제를 만드는 것이었다."),
    dict(slug="col-pressian-isekai-4", title="21세기 단군신화? 기업은 '시민'이 될 수 있을까",
         publication="프레시안 특집 [이세계 민주주의 교실]", year="2024", month="2", day="8", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024020814521279229",
         excerpt="지구가 아닌 이세계에서 눈을 뜬 당신 앞에 주어진 과제는 '마법으로 드래곤 사냥하기'가 아닌, 평범한 사람들이 모여 공동의 문제를 해결할 '도구'로서의 정치체제를 만드는 것이었다."),
    dict(slug="col-pressian-isekai-5", title="인공지능을 정치에 어떻게 활용해 볼까?",
         publication="프레시안 특집 [이세계 민주주의 교실]", year="2024", month="2", day="8", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024020814560006080",
         excerpt="지구가 아닌 이세계에서 눈을 뜬 당신 앞에 주어진 과제는 '마법으로 드래곤 사냥하기'가 아닌, 평범한 사람들이 모여 공동의 문제를 해결할 '도구'로서의 정치체제를 만드는 것이었다."),
    # -- 프레시안 특집 [신년특별기고 - 송경호의 'AI 정치'] (series, 2024.01.03) --
    dict(slug="col-pressian-aipolitics-1", title="AI로 정치인 대체하자? 'IT 강령술사'가 등장한다",
         publication="프레시안 특집 [신년특별기고 - 송경호의 'AI 정치']", year="2024", month="1", day="3", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024010317011669947",
         excerpt="인공지능 기술의 발전은 우리의 삶을 근본적으로 변화시키고 있다. 정치 역시 예외는 아니다. 인간의 정치에 인공지능을 활용하는 것을 넘어, 인공지능에게 정치를 맡긴다면 어떻게 될까?"),
    dict(slug="col-pressian-aipolitics-2", title="'서울-양평고속도로'의 최적안을 결정할 AI가 나온다면?",
         publication="프레시안 특집 [신년특별기고 - 송경호의 'AI 정치']", year="2024", month="1", day="3", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024010317042031233",
         excerpt="인공지능 기술의 발전은 우리의 삶을 근본적으로 변화시키고 있다. 정치 역시 예외는 아니다."),
    dict(slug="col-pressian-aipolitics-3", title="'철인군주AI'로 정치를 대체하자?",
         publication="프레시안 특집 [신년특별기고 - 송경호의 'AI 정치']", year="2024", month="1", day="3", section="칼럼", kind="post",
         sourceUrl="https://m.pressian.com/m/pages/articles/2024010317072429864",
         excerpt="인공지능 기술의 발전은 우리의 삶을 근본적으로 변화시키고 있다. 정치 역시 예외는 아니다."),
    # -- 통일연구원 이슈브리프 (신규 4건, 149호는 이미 마이그레이션됨) --
    dict(slug="col-yinks-157", title="최근 북한 「로동신문」의 인권관련 보도 경향",
         publication="연세대 통일연구원", year="2023", section="이슈브리프", kind="post",
         sourceUrl="https://www.yinks.or.kr/post/제157호-송경호-전문연구원-최근-북한-「로동신문」의-인권관련-보도-경향",
         excerpt="최근 북한 언론에서 '인권'은 어떤 맥락에서 어떤 방식으로 다루어지고 있을까?"),
    dict(slug="col-yinks-161", title="대통령 연설문에 나타난 '북한동포' 인식의 변화",
         publication="연세대 통일연구원", year="2023", section="이슈브리프", kind="post",
         sourceUrl="https://www.yinks.or.kr/post/제161호-송경호-전문연구원-대통령-연설문에-나타난-북한동포-인식의-변화",
         excerpt="과거 우리 사회에서 북한사람들은 '동포(同胞)'로 표현됐다."),
    dict(slug="col-yinks-169", title="북한을 탈출한 사람들은 어떻게 명명되었는가?: 1990-2024년 빅카인즈 데이터에 대한 기초 분석",
         publication="연세대 통일연구원", year="2024", section="이슈브리프", kind="post",
         sourceUrl="https://www.yinks.or.kr/post/제169호-송경호-전문연구원-북한을-탈출한-사람들은-어떻게-명명되었는가-1990-2024년-빅카인즈-데이터에-대한-기초-분석",
         excerpt="2024년 2월 21일, 대통령직속 국민통합위원회는 「북배경주민과의 동행」 특별위원회 출범식을 열었다."),
    dict(slug="col-yinks-183", title="프론티어 없는 위협: 북한의 인공지능 역량 검증의 사각지대",
         publication="연세대 통일연구원", year="2026", section="이슈브리프", kind="post",
         sourceUrl="https://www.yinks.or.kr/post/제183호-송경호-전문연구원-프론티어-없는-위협-북한의-인공지능-역량-검증의-사각지대",
         excerpt="북한의 인공지능(AI) 역량은 최근 몇 년 사이 북한·안보 연구의 핵심 주제로 부상했다."),
    # -- 경향신문 [공감] (2023, monthly) --
    dict(slug="col-khan-2023-01", title="[공감] 포퓰리즘이 뭐라고 생각하세요",
         publication="경향신문 [공감]", year="2023", month="1", day="18", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202301180300065",
         excerpt="온갖 포퓰리즘이 난무한다."),
    dict(slug="col-khan-2023-02", title="[공감] 세계시민주의는 실패한 걸까",
         publication="경향신문 [공감]", year="2023", month="2", day="15", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202302150300045",
         excerpt="베트남 냐짱에 왔다. 밤늦게 출발해 새벽에 도착하는 고된 비행 일정이었다."),
    dict(slug="col-khan-2023-03", title="[공감] 대표란 무엇인가",
         publication="경향신문 [공감]", year="2023", month="3", day="15", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202303150300035",
         excerpt="대표가 위기다. 거대 양당은 하루가 멀다 하고 상대 당대표를 공격한다."),
    dict(slug="col-khan-2023-04", title="[공감] 정치학이 쓸모가 있나요",
         publication="경향신문 [공감]", year="2023", month="4", day="12", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202304120300065",
         excerpt="\"정치학 전공하면 나중에 정치할 건가?\" 숱하게 받아온 질문이다."),
    dict(slug="col-khan-2023-05", title="[공감] 어버이날, 가족의 의미를 다시 생각하다",
         publication="경향신문 [공감]", year="2023", month="5", day="10", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202305100300065",
         excerpt="아침부터 첫째 아이를 혼냈다."),
    dict(slug="col-khan-2023-06", title="[공감] 그것은 우리가 원하는 우리 모습이 아니다",
         publication="경향신문 [공감]", year="2023", month="6", day="7", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202306070300065",
         excerpt="우리 집에는 많은 규칙이 있다."),
    dict(slug="col-khan-2023-07", title="[공감] 임금 노릇 하기도 어렵고 신하 노릇 하기도 쉽지 않다",
         publication="경향신문 [공감]", year="2023", month="7", day="5", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202307050300065",
         excerpt="잠자리에 누웠던 첫째가 대성통곡했다."),
    dict(slug="col-khan-2023-08", title="[공감] 인공지능시대, 문과가 필요할까",
         publication="경향신문 [공감]", year="2023", month="8", day="1", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202308012031005",
         excerpt="초등학교 4학년 첫째의 꿈은 요리사다."),
    dict(slug="col-khan-2023-09", title="[공감] 그건 정치가 아니다",
         publication="경향신문 [공감]", year="2023", month="8", day="29", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202308292030015",
         excerpt="우리 애들은 간판과 현수막으로 한글을 깨쳤다."),
    dict(slug="col-khan-2023-10", title="[공감] 어려울 때 도와주는 친구가 진정한 친구다",
         publication="경향신문 [공감]", year="2023", month="9", day="26", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202309262023015",
         excerpt="지난 주말, 한국에서 공부하는 미국·일본·중국 대학원생들과 부산에 다녀왔다."),
    dict(slug="col-khan-2023-11", title="[공감] 적대주의를 넘어 서로 함께 살아가기",
         publication="경향신문 [공감]", year="2023", month="10", day="24", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202310242027015",
         excerpt="우리 집에는 매일 전투가 벌어진다."),
    dict(slug="col-khan-2023-12", title="[공감] 기후위기에 함께 적응하기",
         publication="경향신문 [공감]", year="2023", month="11", day="21", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202311212040015",
         excerpt="둘째가 밤새 기침하는 통에 잠을 설쳤다."),
    dict(slug="col-khan-2023-13", title="[공감] 가장 외로운 시대의 인공지능",
         publication="경향신문 [공감]", year="2023", month="12", day="19", section="칼럼", kind="post",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202312192019015",
         excerpt="벌써 몇년 된 일이다. 일본에서 고장난 로봇 강아지 아이보(aibo)를 위한 합동 장례식이 열렸다."),
    # -- newly found while auditing for missed items (2026-08-21) --
    dict(slug="col-miri518-2023", title="5·18국제연구원에 바란다: 자유, 정의, 민주, 인권, 평화 연구로 확장해 가자",
         publication="MIRI REPORT 2023", year="2023", section="칼럼", kind="post",
         sourceUrl="https://miri518.or.kr/index.do?command=view&wr_id=120&contentId=dc9bc9de795f22cee75061dc2d0b5d9cafe1c32e9e6c7660e57e30b197505d2d",
         excerpt=None),
    dict(slug="col-point-2024-03", title="중경삼림: 자유가 없는 권력은 폭력에 불과하다",
         publication="PO.INT 2024년 3월호", year="2024", month="3", section="에세이", kind="post",
         sourceUrl="http://www.kpsa.or.kr/contents/bbs/bbs_content.html?bbs_cls_cd=002002002&cid=24040817095362&bbs_type=B",
         excerpt=None),
    dict(slug="col-unipress-antagonism-2023", title="‘적대주의 정치’에 대한 이해와 해법",
         publication="대학지성 In&Out", year="2023", month="2", day="4", section="이슈브리프", kind="post",
         sourceUrl="https://www.unipress.co.kr/news/articleView.html?idxno=7851",
         excerpt="경제·인문사회연구회 인문정책연구총서 〈'적대주의 정치'에 대한 이해와 해법〉(연구책임자: 김만권)에 참여 연구자로 기여한 정책연구보고서를 소개하는 기사."),
    dict(slug="press-unn-bk21-2025", title="4단계 BK21 우수 참여인력 29명 표창…네이처 논문 게재 등 성과 '괄목'",
         publication="한국대학신문", year="2025", month="2", day="19", section="보도", kind="press",
         sourceUrl="https://news.unn.net/news/articleView.html?idxno=575220",
         excerpt="4단계 BK21 사업 우수 참여인력 표창 시상식 보도로, 그가 수상자 명단에 포함되었다."),
    dict(slug="press-charhar-wechat-2021", title="中日韩专家齐聚，共商\"经济权与健康权\"维护",
         publication="察哈尔学会 (WeChat)", year="2021", month="10", day="21", section="보도", kind="press",
         sourceUrl="https://mp.weixin.qq.com/s/ZD0ZAFizfCF5CVQiXAC7XA",
         excerpt="지린대·시베이정법대 인권연구센터가 주최한 「경제권과 건강권 수호 국제토론회」(2021.10.21)에서 그가 「코로나19로 인한 한국의 경제권·건강권 인식 변화」를 발표했다는 보도."),
    dict(slug="press-jlu-humanrights-wechat-2021", title="前沿 | 我中心主办\"经济权与健康权维护\"国际研讨会",
         publication="吉林大学人权研究中心 启航1949 (WeChat)", year="2021", month="10", day="21", section="보도", kind="press",
         sourceUrl="https://mp.weixin.qq.com/s/zHZ6787-e9bqqxBdHOZ0bw",
         excerpt="지린대 인권연구센터가 주최한 같은 토론회에 대한 상세 보도로, 그의 발표 내용을 별도로 소개했다."),
    dict(slug="col-naeil-2012", title="손가락이 아닌 달을 보라",
         publication="내일신문", year="2012", section="칼럼", kind="post",
         sourceUrl="https://n.news.naver.com/mnews/article/086/0002113868?sid=110",
         excerpt="얼마 전 마이클 샌델 교수가 내한했다. 자의 반 타의 반으로 그의 강연을 보게 되었는데 엄청난 인파에 놀랐다."),
    # -- press/interview coverage found on Facebook and News1 while auditing (2026-08-21) --
    dict(slug="press-uic-fb-2022", title="Professor Interview",
         publication="Underwood International College, Yonsei University (Facebook)", year="2022", month="12", day="28", section="보도", kind="press",
         sourceUrl="https://www.facebook.com/UIC.YonseiUniversity/posts/pfbid0nNpjZt32fEpjAzPWosrKivmSFa8iHcM9oVTDEFsE4BSBxtedqPERaMxThGnbor5dl",
         excerpt="Professor Song is a three time Yonsei alumni and has watched the university grow and flourish in his time here."),
    dict(slug="press-yonjeong-interview-2022", title="2학기 Knock Knock(樂樂) 연구실 문이 열렸습니다: 송경호 교수님과의 인터뷰",
         publication="연세대학교 정치외교학과 학생회 「위하여」 (Facebook)", year="2022", month="11", day="7", section="보도", kind="press",
         sourceUrl="https://www.facebook.com/yonjeong1945/posts/pfbid02C1jmuyDvUsbyKeHyP2yh2pU6KnZH7RAYLDg5JsMo3bGrr9jwZtNuzG8nKuvQuUXTl",
         excerpt="1학기에 황태희 교수님과 진행했던 낙낙 연구실 문이 열렸습니다가 송경호 교수님과의 인터뷰와 함께 돌아왔습니다."),
    dict(slug="press-yonjeong-bookrec-2022", title="송경호 교수님의 책 추천",
         publication="연세대학교 정치외교학과 학생회 「위하여」 (Facebook)", year="2022", month="11", day="7", section="보도", kind="press",
         sourceUrl="https://www.facebook.com/yonjeong1945/posts/pfbid02ng5T9SkA52JZuPbHpbMMptQ6gzJQY5pkchtqGrWLPJS2P911o4zi25L72ct7cWN6l",
         excerpt=None),
    dict(slug="press-news1-2023", title="오늘날의 동아시아 시민사회-일본, 중국, 미얀마, 한국을 중심으로",
         publication="뉴스1", year="2023", month="8", day="9", section="보도", kind="press",
         sourceUrl="https://www.news1.kr/photos/details/?6150533",
         excerpt="참여사회연구소 토론회 현장 사진 보도."),
    dict(slug="col-khan-notice-2023", title="[알림] 오피니언면, 더 품격 있는 공론장으로",
         publication="경향신문", year="2023", month="1", day="15", section="보도", kind="press",
         sourceUrl="https://www.khan.co.kr/opinion/column/article/202301152058005",
         excerpt="경향신문이 오피니언면을 개편하며 [공감] 필진 소개를 공지한 사고(社告)."),
    # -- press coverage about him (report/interview - not written by him) --
    dict(slug="press-newstheai-2025", title="AI 안전 서울 포럼 참석한 앤트로픽 \"AI 안전, 사회 전체 노력 필요\"",
         publication="뉴스디에이아이", year="2025", month="10", day="28", section="보도", kind="press",
         sourceUrl="https://www.newstheai.com/news/articleView.html?idxno=9497", excerpt=None),
    dict(slug="press-henkaku-2025", title="The Henkaku Center's First AI Safety Workshop",
         publication="Henkaku Center", year="2025", month="8", day="11", section="보도", kind="press",
         sourceUrl="https://www.henkaku.center/en/news/reports/2025-08-11/workshop-2025-07-05-AI-Safety/", excerpt=None),
    dict(slug="press-nate-2025", title="\"AI 시대, 교육은 어디로?\"…디지털소사이어티, 세미나 개최",
         publication="네이트뉴스", year="2025", month="6", day="29", section="보도", kind="press",
         sourceUrl="https://news.nate.com/view/20250629n04222", excerpt=None),
    dict(slug="press-catholicnews-2025", title="\"청년 남성들은 정말 '극우'일까\"",
         publication="가톨릭뉴스", year="2025", month="5", day="20", section="보도", kind="press",
         sourceUrl="https://www.catholicnews.co.kr/news/articleView.html?idxno=34375", excerpt=None),
    dict(slug="press-catholictimes-2025", title="\"청년 남성은 우파?\"…편견 벗어나 이해의 폭 넓히는 자리 마련",
         publication="가톨릭타임즈", year="2025", month="5", day="18", section="보도", kind="press",
         sourceUrl="https://www.catholictimes.org/article/20250518500016", excerpt=None),
    dict(slug="press-etnews-2024", title="[AI 정치 선진화 포럼] \"AI 활용해 국민불신 없애고, 정치 개혁 이뤄내야\"",
         publication="전자신문", year="2024", month="5", day="16", section="보도", kind="press",
         sourceUrl="https://www.etnews.com/20240516000324", excerpt=None),
    dict(slug="press-kyosu-2024", title="돌봄의 기술을 탐구하다…AI와 로봇이 만드는 미래의 윤리적 재구성",
         publication="교수신문", year="2024", month="12", day="16", section="보도", kind="press",
         sourceUrl="https://www.kyosu.net/news/articleView.html?idxno=128899", excerpt=None),
    dict(slug="press-kyosu-2023-1", title="편향된 '신자유주의 비판'…\"디지털 대응은 소홀\"",
         publication="교수신문", year="2023", month="8", day="28", section="보도", kind="press",
         sourceUrl="https://www.kyosu.net/news/articleView.html?idxno=108807", excerpt=None),
    dict(slug="press-kyosu-2023-2", title="'AI 시대, 인문학은 정말 위기인가: 도래할 뉴리버럴아츠' 학술토론회 열린다",
         publication="교수신문", year="2023", month="8", day="18", section="보도", kind="press",
         sourceUrl="https://www.kyosu.net/news/articleView.html?idxno=108548", excerpt=None),
    dict(slug="press-kyosu-2022-1", title="\"지역정치 역할은 확대…정치학은 능동 대처 못해\"",
         publication="교수신문", year="2022", month="5", day="31", section="보도", kind="press",
         sourceUrl="https://www.kyosu.net/news/articleView.html?idxno=89320", excerpt=None),
    dict(slug="press-kyosu-2022-2", title="'휴먼 라이츠'는 어떻게 '천부인권'이 됐을까",
         publication="교수신문", year="2022", month="6", day="15", section="보도", kind="press",
         sourceUrl="https://www.kyosu.net/news/articleView.html?idxno=89798", excerpt=None),
    dict(slug="press-kyosu-2022-3", title="\"메이지 일본, 서양의 문법적 관점에서 자신의 언어를 사유하기 시작했다\"",
         publication="교수신문", year="2022", month="1", day="25", section="보도", kind="press",
         sourceUrl="https://www.kyosu.net/news/articleView.html?idxno=84364", excerpt=None),
    dict(slug="press-newsis-2020", title="\"5·18 인권침해 연구 시급…차별·혐오 역사 단절해야\"",
         publication="뉴시스", year="2020", month="5", day="26", section="보도", kind="press",
         sourceUrl="https://www.newsis.com/view/?id=NISX20200526_0001037801", excerpt=None),
    dict(slug="press-topstarnews-2020", title="\"5·18 인권침해 연구 시급…차별·혐오 역사 단절해야\"",
         publication="톱스타뉴스", year="2020", month="5", day="26", section="보도", kind="press",
         sourceUrl="https://www.topstarnews.net/news/articleView.html?idxno=791444", excerpt=None),
]


def main():
    existing = json.loads(SRC.read_text(encoding="utf-8"))
    for item in existing:
        item.setdefault("kind", "post")
        item.setdefault("month", None)
        item.setdefault("day", None)
        item.setdefault("note", None)

    for entry in NEW_ENTRIES:
        # most NEW_ENTRIES only ever have a short excerpt + a live
        # sourceUrl to link out to; a few (the outlet itself is gone) get
        # their full text supplied directly via "body" instead, and read
        # as a complete page rather than an excerpt-plus-outlink stub
        body = entry.get("body") or ([entry["excerpt"]] if entry.get("excerpt") else [])
        migration_status = "상세 페이지 완료" if entry.get("body") else "외부 링크만 (전문 미이전)"
        existing.append({
            "logNo": None,
            "slug": entry["slug"],
            "title": entry["title"],
            "rawTitle": entry["title"],
            "publication": entry["publication"],
            "issue": None,
            "year": entry["year"],
            "month": entry.get("month"),
            "day": entry.get("day"),
            "naverCategory": None,
            "section": entry["section"],
            "sourceUrl": entry["sourceUrl"],
            "naverImportedAt": None,
            "image": None,
            "imageSource": None,
            "body": body,
            "kind": entry["kind"],
            "note": entry.get("note"),
            "migrationStatus": migration_status,
        })

    existing.sort(key=lambda d: (-int(d["year"]), d["title"]))
    DST.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"total writing-archive entries: {len(existing)} (added {len(NEW_ENTRIES)})")


if __name__ == "__main__":
    main()
